apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-apps
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 2
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:8.2.6
        ports:
        - containerPort: 3000
